rate: 50

# For a robot that uses base_footprint, change base_frame to base_footprint
# base_frame: base_link
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.122
wheel_track: 0.524
encoder_resolution: 3591.84 # 74.83 gearbox * 2 sensors * 6 magnets * quadrature
gear_reduction: 1.0
motors_reversed: False

# === PID parameters
Kp: 30
Kd: 20
Ki: 0
Ko: 20
accel_limit: 1.0

sensors: {
}
